import {
  proxyActivities,
  defineSignal,
  setHandler,
  condition,
  continueAsNew,
  sleep,
} from "@temporalio/workflow";
import type { IngestSupportMessageInput } from "@shared/types";
import type * as activities from "../activities/index.js";

/** Signal to push a new inbound message into the workflow for processing. */
export const inboundMessageSignal = defineSignal<[IngestSupportMessageInput]>("inboundMessage");

/** Signal to gracefully shut down the workflow (stops accepting messages). */
export const shutdownSignal = defineSignal("shutdown");

const MAX_EVENTS_BEFORE_CONTINUE_AS_NEW = 500;
const DRAIN_TIMEOUT_MS = 5_000;
const MESSAGE_COOLDOWN_MS = 5_000;

const {
  ingestSupportMessage,
  checkAutoGenerateDraft,
  generateReplyDraft,
} = proxyActivities<typeof activities>({
  startToCloseTimeout: "30 seconds",
  retry: { maximumAttempts: 3 },
});

/**
 * Long-running workflow for a single Discord channel connection.
 *
 * The Discord bot signals this workflow with each inbound message.
 * The workflow processes messages sequentially, triggering auto-draft
 * generation when configured. After processing MAX_EVENTS_BEFORE_CONTINUE_AS_NEW
 * messages it calls continueAsNew to reset event history and avoid
 * hitting Temporal's history size limit.
 *
 * @param channelConnectionId - The channel connection this workflow serves.
 * @param processedCount - Running total across continueAsNew cycles (carry-over).
 */
export async function ingestSupportMessageWorkflow(
  channelConnectionId: string,
  processedCount: number = 0,
): Promise<void> {
  const queue: IngestSupportMessageInput[] = [];
  let shuttingDown = false;
  let processed = processedCount;

  setHandler(inboundMessageSignal, (msg: IngestSupportMessageInput) => {
    if (!shuttingDown) {
      queue.push(msg);
    }
  });

  setHandler(shutdownSignal, () => {
    shuttingDown = true;
  });

  // Main processing loop
  while (!shuttingDown) {
    // Wait until there's a message in the queue or shutdown is requested
    await condition(() => queue.length > 0 || shuttingDown);

    // Drain all queued messages with a cooldown between each
    while (queue.length > 0) {
      const msg = queue.shift()!;

      const { conversationId, isNew } = await ingestSupportMessage(msg);
      processed++;

      if (isNew) {
        const shouldGenerate = await checkAutoGenerateDraft(conversationId);
        if (shouldGenerate) {
          await generateReplyDraft({ conversationId });
        }
      }

      // ContinueAsNew to reset event history before it grows too large
      if (processed >= MAX_EVENTS_BEFORE_CONTINUE_AS_NEW) {
        // Drain any remaining queued messages first
        for (const remaining of queue) {
          await sleep(MESSAGE_COOLDOWN_MS);
          const res = await ingestSupportMessage(remaining);
          if (res.isNew) {
            const shouldGen = await checkAutoGenerateDraft(res.conversationId);
            if (shouldGen) {
              await generateReplyDraft({ conversationId: res.conversationId });
            }
          }
        }
        queue.length = 0;

        await continueAsNew<typeof ingestSupportMessageWorkflow>(
          channelConnectionId,
          0,
        );
      }

      // Cooldown between messages to avoid overwhelming the database
      if (queue.length > 0) {
        await sleep(MESSAGE_COOLDOWN_MS);
      }
    }
  }

  // Shutting down: drain remaining messages with a timeout
  if (queue.length > 0) {
    await condition(() => false, DRAIN_TIMEOUT_MS).catch(() => {});
    for (let i = 0; i < queue.length; i++) {
      if (i > 0) await sleep(MESSAGE_COOLDOWN_MS);
      const msg = queue[i]!;
      const { conversationId, isNew } = await ingestSupportMessage(msg);
      if (isNew) {
        const shouldGenerate = await checkAutoGenerateDraft(conversationId);
        if (shouldGenerate) {
          await generateReplyDraft({ conversationId });
        }
      }
    }
  }
}
