import { proxyActivities } from "@temporalio/workflow";
import type * as activities from "../activities/index.js";

export interface IngestSupportMessageInput {
  channelConnectionId: string;
  externalMessageId: string;
  externalUserId: string;
  username: string | null;
  displayName: string | null;
  body: string;
  timestamp: string;
  rawPayload: Record<string, unknown>;
  externalThreadId: string | null;
}

const {
  ingestSupportMessage,
  checkAutoGenerateDraft,
  generateReplyDraft,
} = proxyActivities<typeof activities>({
  startToCloseTimeout: "30 seconds",
  retry: { maximumAttempts: 3 },
});

export async function ingestSupportMessageWorkflow(
  input: IngestSupportMessageInput
): Promise<{ conversationId: string; draftGenerated: boolean }> {
  const { conversationId, isNew } = await ingestSupportMessage(input);

  let draftGenerated = false;

  // Auto-generate draft if enabled and this is a new message
  if (isNew) {
    const shouldGenerate = await checkAutoGenerateDraft(conversationId);
    if (shouldGenerate) {
      await generateReplyDraft({ conversationId });
      draftGenerated = true;
    }
  }

  return { conversationId, draftGenerated };
}
