import { prisma } from "@shared/database";
import type { IngestSupportMessageInput } from "@shared/types";

export async function ingestSupportMessage(input: IngestSupportMessageInput): Promise<{
  conversationId: string;
  isNew: boolean;
}> {
  const channelConnection = await prisma.channelConnection.findUnique({
    where: { id: input.channelConnectionId },
  });

  if (!channelConnection) {
    throw new Error(`Channel connection not found: ${input.channelConnectionId}`);
  }

  // Check idempotency
  const existing = await prisma.conversationMessage.findFirst({
    where: {
      channelConnectionId: input.channelConnectionId,
      externalMessageId: input.externalMessageId,
    },
  });

  if (existing) {
    return { conversationId: existing.conversationId, isNew: false };
  }

  // Upsert customer identity
  let identity = await prisma.customerChannelIdentity.findUnique({
    where: {
      channelConnectionId_externalUserId: {
        channelConnectionId: input.channelConnectionId,
        externalUserId: input.externalUserId,
      },
    },
  });

  if (!identity) {
    const profile = await prisma.customerProfile.create({
      data: {
        workspaceId: channelConnection.workspaceId,
        displayName: input.displayName ?? input.username ?? input.externalUserId,
      },
    });

    identity = await prisma.customerChannelIdentity.create({
      data: {
        customerProfileId: profile.id,
        channelConnectionId: input.channelConnectionId,
        externalUserId: input.externalUserId,
        username: input.username,
        displayName: input.displayName,
      },
    });
  }

  // Find or create conversation
  let conversation = input.externalThreadId
    ? await prisma.conversation.findFirst({
        where: {
          workspaceId: channelConnection.workspaceId,
          customerProfileId: identity.customerProfileId,
          externalThreadId: input.externalThreadId,
          status: { notIn: ["CLOSED"] },
        },
      })
    : null;

  if (!conversation) {
    conversation = await prisma.conversation.findFirst({
      where: {
        workspaceId: channelConnection.workspaceId,
        customerProfileId: identity.customerProfileId,
        primaryChannelType: channelConnection.type,
        status: { notIn: ["CLOSED"] },
      },
      orderBy: { lastMessageAt: { sort: "desc", nulls: "last" } },
    });
  }

  const now = new Date();
  let isNew = false;

  if (!conversation) {
    conversation = await prisma.conversation.create({
      data: {
        workspaceId: channelConnection.workspaceId,
        customerProfileId: identity.customerProfileId,
        primaryChannelType: channelConnection.type,
        status: "NEW",
        subject: input.body.slice(0, 100),
        externalThreadId: input.externalThreadId,
        lastMessageAt: now,
        lastInboundAt: now,
      },
    });
    isNew = true;
  } else {
    conversation = await prisma.conversation.update({
      where: { id: conversation.id },
      data: { lastMessageAt: now, lastInboundAt: now, status: "WAITING_REVIEW" },
    });
  }

  // Store message
  await prisma.conversationMessage.create({
    data: {
      conversationId: conversation.id,
      channelConnectionId: input.channelConnectionId,
      direction: "INBOUND",
      senderKind: "CUSTOMER",
      externalMessageId: input.externalMessageId,
      body: input.body,
      rawPayloadJson: input.rawPayload as Record<string, unknown> as never,
      sentAt: new Date(input.timestamp),
    },
  });

  return { conversationId: conversation.id, isNew };
}

export async function checkAutoGenerateDraft(conversationId: string): Promise<boolean> {
  const conversation = await prisma.conversation.findUnique({
    where: { id: conversationId },
  });

  if (!conversation) return false;

  const config = await prisma.workspaceAgentConfig.findUnique({
    where: { workspaceId: conversation.workspaceId },
  });

  return config?.enabled === true && config?.autoDraftOnInbound === true;
}
